version: "3.9"
name: xavi-social-datastore

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: xavi_social
      POSTGRES_USER: xavi_social
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
    ports: ["127.0.0.1:5432:5432"]
    restart: unless-stopped
    networks:
      default:
        aliases: [postgres]

  redis:
    image: redis:7-alpine
    command: ["redis-server","--save","60","1000","--appendonly","yes"]
    volumes:
      - ../../data/redis:/data
    ports: ["127.0.0.1:6379:6379"]
    restart: unless-stopped
    networks:
      default:
        aliases: [redis]

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ../../data/minio:/data
    ports:
      - "127.0.0.1:9000:9000" # S3
      - "127.0.0.1:9001:9001" # Console
    restart: unless-stopped
    networks:
      default:
        aliases: [minio]

networks:
  default:
    name: xavi-social-datastore_default
